### ISSUE TITLE
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14

### ISSUE THREAD

**Issue by dakuohaozyj** [williamyang1991/Rerender_A_Video#78]
I can download other resource packages, but this resource cannot be downloaded. Where is the setting path? I changed it to an absolute path， Thanks

Please do not close the issue if the issue is not resolved.

**Comment by williamyang1991** [comment]
I think this is not the problem of my code. This part is the official code of ControlNet. 
I am not responsible for solving the issues on the code related to other project. For such kind of issues, maybe you can search it yourself or raise an issues in the corresponding project page (https://github.com/lllyasviel/ControlNet/issues). 
I have no idea where the setting path is. If you ask me, what I could do is also just to search the solution through baidu or google (Acutally, the first result of google can solve your problem https://huggingface.co/openai/clip-vit-large-patch14). 

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/18130694/5cb24058-443c-4da3-98f3-ef4e33f9c065)

**Comment by dakuohaozyj** [comment]
It directly affects the use of our products. You can download the model
manually. Where do you need to modify it after downloading? I hope to get
your help.


Shuai Yang ***@***.***>于2023年10月11日 周三16:53写道：

**Comment by williamyang1991** [comment]
> It directly affects the use of our products. 

It's your products, not my products. I'm not responsible for your products.\
BTW, for using our model in your products, please follow the [S-Lab license](https://github.com/williamyang1991/Rerender_A_Video/blob/main/LICENSE.md).

> You can download the model manually. 

I cannot understand what you mean by `you can download the model manually`. You or I?

> Where do you need to modify it after downloading? I hope to get your help. 

I have said I have no idea since this part is directly imported from other project. The code is not written by me. 
I'm sorry I cannot help you with this issue.
From my perspective, your problem is because that your network is blocked from the huggingface. You should check your network (e.g., 翻墙), which is however, out of my scope.

**Comment by dakuohaozyj** [comment]
I don't have a product. The product I mentioned refers to this open source
project.


Shuai Yang ***@***.***>于2023年10月11日 周三17:56写道：

**Comment by williamyang1991** [comment]
So you mean `It directly affects the use of this open source product.`
But I don't think so. I think it's your network issue that affects the use.

And I have also provided a solution for you in https://github.com/williamyang1991/Rerender_A_Video/issues/77#issuecomment-1756962724, which however you might ignore.

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/18130694/b40bc78a-448d-49cd-b7cb-f1e4ec8129d5)

You can either fix your network or search all `openai/clip-vit-large-patch14` throughout the whole files in this project and replace them with your path.

I think I have provided enough information to solve this issue. 
I will close this issue.
